# Prometheus alerting rules for Eliza AI
groups:
  - name: eliza_health_alerts
    interval: 30s
    rules:
      - alert: ElizaSystemDown
        expr: eliza_system_operational == 0
        for: 2m
        labels:
          severity: critical
          component: system
        annotations:
          summary: "Eliza AI system is down"
          description: "The Eliza AI system has been non-operational for more than 2 minutes"

      - alert: ElizaHealthScoreLow
        expr: eliza_health_score < 50
        for: 5m
        labels:
          severity: warning
          component: health
        annotations:
          summary: "Eliza health score is low"
          description: "System health score is {{ $value }}%, below threshold of 50%"

      - alert: ElizaHealthScoreCritical
        expr: eliza_health_score < 30
        for: 2m
        labels:
          severity: critical
          component: health
        annotations:
          summary: "Eliza health score is critical"
          description: "System health score is {{ $value }}%, critically low"

  - name: eliza_execution_alerts
    interval: 1m
    rules:
      - alert: ElizaPythonExecutionFailureRateHigh
        expr: eliza_python_success_rate_percent < 70
        for: 5m
        labels:
          severity: warning
          component: python_executor
        annotations:
          summary: "Python execution failure rate is high"
          description: "Success rate is {{ $value }}%, below 70% threshold"

      - alert: ElizaPythonExecutionSlowdown
        expr: eliza_python_execution_time_avg_ms > 10000
        for: 5m
        labels:
          severity: warning
          component: python_executor
        annotations:
          summary: "Python execution time is slow"
          description: "Average execution time is {{ $value }}ms, above 10 second threshold"

      - alert: ElizaPythonExecutionStalled
        expr: rate(eliza_python_executions_total[5m]) == 0 and eliza_tasks_by_status{status="PENDING"} > 0
        for: 10m
        labels:
          severity: critical
          component: python_executor
        annotations:
          summary: "Python executions have stalled"
          description: "No Python executions in the last 10 minutes despite pending tasks"

  - name: eliza_agent_alerts
    interval: 1m
    rules:
      - alert: ElizaNoActiveAgents
        expr: eliza_agents_total == 0
        for: 5m
        labels:
          severity: critical
          component: agents
        annotations:
          summary: "No active agents detected"
          description: "The system has no registered agents"

      - alert: ElizaAgentsInErrorState
        expr: eliza_agents_by_status{status="ERROR"} > 0
        for: 3m
        labels:
          severity: warning
          component: agents
        annotations:
          summary: "Agents in error state"
          description: "{{ $value }} agent(s) are in ERROR state"

      - alert: ElizaAllAgentsIdle
        expr: eliza_agents_by_status{status="IDLE"} == eliza_agents_total and eliza_tasks_by_status{status="PENDING"} > 5
        for: 10m
        labels:
          severity: warning
          component: agents
        annotations:
          summary: "All agents idle with pending work"
          description: "All agents are idle but there are {{ $value }} pending tasks"

  - name: eliza_task_alerts
    interval: 1m
    rules:
      - alert: ElizaHighBlockedTaskCount
        expr: eliza_tasks_by_status{status="BLOCKED"} > 5
        for: 10m
        labels:
          severity: warning
          component: tasks
        annotations:
          summary: "High number of blocked tasks"
          description: "{{ $value }} tasks are currently blocked"

      - alert: ElizaTaskBacklogGrowing
        expr: deriv(eliza_tasks_by_status{status="PENDING"}[10m]) > 0
        for: 15m
        labels:
          severity: warning
          component: tasks
        annotations:
          summary: "Task backlog is growing"
          description: "Pending task count has been increasing for 15 minutes"

      - alert: ElizaHighFailedTaskRate
        expr: rate(eliza_tasks_by_status{status="FAILED"}[10m]) > 0.1
        for: 5m
        labels:
          severity: warning
          component: tasks
        annotations:
          summary: "High task failure rate"
          description: "Task failure rate is {{ $value }} per minute"

  - name: eliza_knowledge_alerts
    interval: 5m
    rules:
      - alert: ElizaKnowledgeBaseEmpty
        expr: eliza_knowledge_entities_total == 0
        for: 30m
        labels:
          severity: info
          component: knowledge
        annotations:
          summary: "Knowledge base is empty"
          description: "The knowledge base has no entities"

  - name: eliza_conversation_alerts
    interval: 2m
    rules:
      - alert: ElizaNoActiveConversations
        expr: eliza_conversations_active == 0
        for: 1h
        labels:
          severity: info
          component: conversations
        annotations:
          summary: "No active conversations"
          description: "There have been no active conversations for over an hour"

      - alert: ElizaConversationSpike
        expr: rate(eliza_conversations_active[5m]) > 10
        for: 3m
        labels:
          severity: info
          component: conversations
        annotations:
          summary: "Conversation activity spike"
          description: "Conversation creation rate is unusually high: {{ $value }} per minute"
